# Generated by Django 5.2.10 on 2026-01-15 10:12

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location_name', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geo_bucket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='geo.geobucket')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['location'], name='properties__locatio_2b40b0_idx'), models.Index(fields=['geo_bucket'], name='properties__geo_buc_903c76_idx')],
            },
        ),
    ]
